services:
  - type: web
    name: structure-backend
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: security.jwt.secret-key
        sync: false
      - key: security.jwt.expiration-time
        value: 86400000