# Configuration du Serveur
server.port=${PORT:8081}
server.forward-headers-strategy=framework
spring.application.name=Structure-Backend

# Configuration Base de Données (MySQL/MariaDB - Local)
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/structure}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuration JWT (Doit correspondre à votre logique de sécurité)
# Assurez-vous que ces clés correspondent à celles utilisées dans votre AuthenticationService
security.jwt.secret-key=votre_clé_secrète_très_longue_et_sécurisée_pour_le_backend_java_256bits
security.jwt.expiration-time=86400000

# Configuration Campost (Environnement de Production)
campost.api-base-url=https://campostpay.cm/api
campost.public-key=04a0fbc2-b742-45d3-a6e4-27d1a5328f56
campost.private-key=9ZlY5Y1uKVzltVlKwYkHa8evIDSsKmpYhMLE1BZMlFAv2Sza5va1nAmcbQoy7ugL